### ISSUE TITLE
BUG-001 - Inconsistent Hover States

### ISSUE THREAD

**Issue by JosephBanham** [lunarcroissant/react-challenge-1-window-news#1]
Raising this as the Footer component doesn't have consistent hover states for the following:

- Data Policy
- Careers
- Sign up to our latest updates

I would recommend that you apply the hover states from the Header component into these links.

**Comment by JosephBanham** [comment]
Also make sure you apply these states to :focus as well! 🙂

**Comment by lunarcroissant** [comment]
Changes made :)
