### ISSUE TITLE
BUG-003 - aXe: Elements must have sufficient colour contrast

### ISSUE THREAD

**Issue by JosephBanham** [lunarcroissant/react-challenge-1-window-news#3]
A number of elements on the page don't meet the necessary Accessibility requirements for colour contrast. I'd do some research into this and see about altering the colour scheme slightly. 

This is important as users with low visibility, vision issues, blurriness or forms of colour blindness rely on good colour contrast to be able to pick out parts of a webpage.

If you need software to test, I'd recommend you look at:

- aXe
- SiteImprove
- WAVE

All are free and are available through the Chrome App Store.

**Comment by lunarcroissant** [comment]
Fixed all using aXe - very useful tool!
