### ISSUE TITLE
BUG-004 - WAVE: Images are missing alternative text

### ISSUE THREAD

**Issue by JosephBanham** [lunarcroissant/react-challenge-1-window-news#4]
It seems that all of the images on the page do not have alt text.

This is important to fix as blind users rely on this alternative text to 'see' the image in their minds.
For example, if I were to say, provide you a description of an image here, you would be able to imagine it.

"Red balloon in the blue sky, with white clouds and a ray of sun."

Please fix. 🙂

**Comment by lunarcroissant** [comment]
All fixed :)
