### ISSUE TITLE
BUG-006 - SiteImprove: Missing H1 on page

### ISSUE THREAD

**Issue by JosephBanham** [lunarcroissant/react-challenge-1-window-news#6]
It's best practice to at least have one instance of H1 on the page. The reason for this is it acts as an anchoring point, or 'origin' for a blind user. I would change the instance of H5 for "Window News" to be a H1 with a H5 CSS class, or change the "Window News" heading to normal text and add a H1 to the site.

**Comment by lunarcroissant** [comment]
Fixed :)
