### ISSUE TITLE
BUG-007 - HeadingsMap: Skipped Headings in the page

### ISSUE THREAD

**Issue by JosephBanham** [lunarcroissant/react-challenge-1-window-news#7]
This is another best practice - Headings should never skip more than one level at a time. This means Headings act like a ladder - You wouldn't go down one two steps at a time, and Headings follow this rule.

Headings are hierarchal, so:

H1 > H2 > H3...

And so on. This also means you can go:

H1 > H2 > H1...

As it's also in hierarchal order.

The Headings in your page go from H5 > H2 > H5. Please fix!

If you need an app to test this, try HeadingsMap. It's free on the Chrome App Store!

**Comment by lunarcroissant** [comment]
Fixed - thanks!
