### ISSUE TITLE
BUG-009 - SiteImprove: Non-distinguishable Landmarks

### ISSUE THREAD

**Issue by JosephBanham** [lunarcroissant/react-challenge-1-window-news#9]
This one's a bit of a doozy with the name alone, so let me break it down for you.

You have multiple instances of 'nav' and 'article' on your page. This is absolutely fine.

... However, when it comes to screenreaders, there's something missing - A label.

Similar to the issues with the forms, blind users who rely on screenreaders cannot differentiate between the different instances as they'll simply hear:

"Article."
"Article."
"Navigation."
"Navigation."
"Navigation."

... You can begin to see why we need labels on these; note that each label needs to be unique as well!

**Comment by lunarcroissant** [comment]
All fixed now :)
